=== MatthewSmit/RayTracer/RayTracer/sceneSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "objects": {
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          { "$ref": "#/definitions/sphere" },
          { "$ref": "#/definitions/torus" },
          { "$ref": "#/definitions/cone" },
          { "$ref": "#/definitions/cylinder" },
          { "$ref": "#/definitions/plane" },
          { "$ref": "#/definitions/polygon" }
        ]
      },
      "uniqueItems": true
    },
    "lights": {
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          { "$ref": "#/definitions/directionLight" }
        ]
      },
      "uniqueItems": true
    },
    "ambientColour": {
      "$ref": "#/definitions/colour"
    },
    "backgroundColour": {
      "$ref": "#/definitions/colour"
    }
  },
  "definitions": {
    "vector": {
      "type": [ "array", "object" ],
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        }
      },
      "minItems": 0,
      "maxItems": 3,
      "additionalProperties": false
    },
    "colour": {
      "type": [ "array", "object" ],
      "properties": {
        "r": {
          "type": "number"
        },
        "g": {
          "type": "number"
        },
        "b": {
          "type": "number"
        },
        "a": {
          "type": "number"
        }
      },
      "minItems": 0,
      "maxItems": 4,
      "additionalProperties": false
    },
    "material": {
      "oneOf": [
        { "$ref": "#/definitions/solidMaterial" },
        { "$ref": "#/definitions/textureMaterial" }
      ]
    },
    "solidMaterial": {
      "properties": {
        "type": {
          "enum": [ "solid" ]
        },
        "colour": {
          "$ref": "#/definitions/colour"
        },
        "reflectivity": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "refractivity": {
          "minimum": -1,
          "maximum": 1
        },
        "specularity": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [ "type", "colour" ]
    },
    "textureMaterial": {
      "properties": {
        "type": {
          "enum": [ "texture" ]
        },
        "path": {
          "type": "string"
        },
        "scaling": {
          "$ref": "#/definitions/vector"
        },
        "specularity": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [ "type", "path" ]
    },
    "sphere": {
      "properties": {
        "type": {
          "enum": [ "sphere" ]
        },
        "position": {
          "$ref": "#/definitions/vector"
        },
        "radius": {
          "type": "number",
          "minimum": 0
        },
        "material": {
          "$ref": "#/definitions/material"
        }
      },
      "additionalProperties": false,
      "required": [ "type", "position", "radius", "material" ]
    },
    "torus": {
      "properties": {
        "type": {
          "enum": [ "torus" ]
        },
        "position": {
          "$ref": "#/definitions/vector"
        },
        "majorRadius": {
          "type": "number",
          "minimum": 0
        },
        "minorRadius": {
          "type": "number",
          "minimum": 0
        },
        "material": {
          "$ref": "#/definitions/material"
        }
      },
      "additionalProperties": false,
      "required": [ "type", "position", "majorRadius", "minorRadius", "material" ]
    },
    "cone": {
      "properties": {
        "type": {
          "enum": [ "cone" ]
        },
        "position": {
          "$ref": "#/definitions/vector"
        },
        "radius": {
          "type": "number",
          "minimum": 0
        },
        "height": {
          "type": "number",
          "minimum": 0
        },
        "material": {
          "$ref": "#/definitions/material"
        }
      },
      "additionalProperties": false,
      "required": [ "type", "position", "radius", "height", "material" ]
    },
    "cylinder": {
      "properties": {
        "type": {
          "enum": [ "cylinder" ]
        },
        "position": {
          "$ref": "#/definitions/vector"
        },
        "radius": {
          "type": "number",
          "minimum": 0
        },
        "height": {
          "type": "number",
          "minimum": 0
        },
        "material": {
          "$ref": "#/definitions/material"
        }
      },
      "additionalProperties": false,
      "required": [ "type", "position", "radius", "height", "material" ]
    },
    "plane": {
      "properties": {
        "type": {
          "enum": [ "plane" ]
        },
        "position": {
          "$ref": "#/definitions/vector"
        },
        "normal": {
          "$ref": "#/definitions/vector"
        },
        "material": {
          "$ref": "#/definitions/material"
        }
      },
      "additionalProperties": false,
      "required": [ "type", "position", "normal", "material" ]
    },
    "polygon": {
      "properties": {
        "type": {
          "enum": [ "polygon" ]
        },
        "points": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/vector"
          },
          "minItems": 3,
          "maxItems": 4,
          "uniqueItems": true
        },
        "texCoords": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/vector"
          },
          "minItems": 3,
          "maxItems": 4
        },
        "material": {
          "$ref": "#/definitions/material"
        }
      },
      "additionalProperties": false,
      "required": [ "type", "points", "material" ]
    },
    "directionLight": {
      "properties": {
        "type": {
          "enum": [ "direction" ]
        },
        "direction": {
          "$ref": "#/definitions/vector"
        },
        "colour": {
          "$ref": "#/definitions/colour"
        }
      },
      "additionalProperties": false,
      "required": [ "type", "direction", "colour" ]
    }
  },
  "additionalProperties": false,
  "required": [ "objects" ]
}

=== MatthewSmit/RayTracer/RayTracer/scene4.json
{
  "objects": [
    {
      "type": "cylinder",
      "position": [ 0, -15, -80 ],
      "radius": 2,
      "height": 5,
      "material": {
        "type": "solid",
        "colour": [ 1, 0, 0, 0 ]
      }
    },
    {
      "type": "cone",
      "position": [ -10, -15, -80 ],
      "radius": 2,
      "height": 5,
      "material": {
        "type": "solid",
        "colour": [ 1, 0, 0, 0 ]
      }
    },
    {
      "type": "sphere",
      "position": [ 0, 15, -80 ],
      "radius": 5,
      "material": {
        "type": "solid",
        "colour": [ 1, 0, 0, 0 ]
      }
    }
  ],
  "ambientColour": [ 0.2, 0.2, 0.2 ],
  "backgroundColour": {},
  "lights": [
    {
      "type": "direction",
      "direction": [ -10, -40, -3 ],
      "colour": [ 1, 1, 1 ]
    }
  ]
}
